/// Exact broadcast identities reviewed against the saved provider and UK guide capture.
/// No generic regions, timeshift inference or provider-created event channels.
nonisolated extension EPGEnrichmentStations {
    static let ukStations: [(names: [String], providerID: String, externalID: String)] = [
        (["BBC ONE LONDON FHD"], "bbconelondon.uk", "BBC.One.Lon.HD.uk"),
        (["BBC ONE SCOTLAND FHD"], "BBCOneScotland.uk", "BBC.One.ScotHD.uk"),
        (["BBC TWO FHD", "BBC TWO HD", "BBC TWO SD"], "BBCTwo.uk", "BBC.Two.HD.uk"),
        (["CHANNEL 4 FHD", "CHANNEL 4 HD", "CHANNEL 4 SD"], "Channel4.uk", "Channel.4.HD.uk"),
        (["CHANNEL 5 FHD", "CHANNEL 5 HD", "CHANNEL 5 SD"], "Channel5.uk", "Channel.5.HD.uk"),
        (["BBC NEWS FHD", "BBC NEWS HD", "BBC NEWS SD"], "BBCNewsChannel.uk", "BBC.NEWS.HD.uk"),
        (["SKY NEWS FHD", "SKY NEWS HD", "SKY NEWS SD"], "SkyNews.uk", "Sky.News.HD.uk"),
        (["Sky Sports Football HD"], "skysportsfootball.uk", "Sky.Sports.Football.HD.uk"),
        (["Sky Sports NFL FHD", "Sky Sports NFL FHD 50FPS", "Sky Sports NFL SD"], "SkySportsAction.uk", "Sky.Sports.NFL.uk"),
        (["TNT SPORTS 1 FHD 50FPS", "TNT Sports 1 FHD"], "TNTSports1.uk", "TNT.Sports.1.HD.uk"),
        (["TNT SPORTS 2 FHD 50FPS", "TNT Sports 2 FHD", "TNT Sports 2 HD"], "TNTSports2.uk", "TNT.Sports.2.HD.uk"),
        (["TNT SPORTS 3 FHD 50FPS", "TNT Sports 3 FHD", "TNT Sports 3 HD"], "TNTSports3.uk", "TNT.Sports.3.HD.uk"),
        (["TNT Sports 4 FHD", "TNT Sports 4 FHD 50FPS", "TNT Sports 4 HD"], "TNTSports4.uk", "TNT.Sports.4.HD.uk"),
        (["BBC ONE WALES FHD"], "BBCOneWales.uk", "BBC.One.Wal.HD.uk"),
        (["BBC ALBA FHD"], "BBCAlba.uk", "BBC.ALBA.HD.uk"),
        (["BBC SCOTLAND FHD", "BBC SCOTLAND HD"], "BBCScotland.uk", "BBCScotlandHD.uk"),
        (["BBC PARLIAMENT FHD"], "BBCParliament.uk", "BBC.Parliament.HD.uk"),
        (["BBC THREE FHD (From 19:00)"], "bbc3.uk", "BBC.Three.HD.uk"),
        (["BBC FOUR (FROM 19:00)"], "bbc4.uk", "BBC.Four.HD.uk"),
        (["CBBC"], "CBBC.uk", "CBBC.HD.uk"),
        (["CBEEBIES (Off Air 19:00)"], "CBeebies.uk", "CBeebies.HD.uk"),
        (["BBC TWO NI HD"], "BBCTwoNorthernIreland.uk", "BBC.Two.NI.HD.uk"),
        (["BBC TWO WALES FHD"], "bbc2wales.uk", "BBC.Two.Wal.HD.uk"),
        (["BBC ONE EAST MIDLANDS FHD"], "bbceastmidlands.uk", "BBC.One.E.Mid.HD.uk"),
        (["BBC ONE NORTH WEST FHD"], "bbcnorthwest.uk", "BBC.One.N.West.HD.uk"),
        (["BBC ONE NORTH EAST & CUMBRIA FHD"], "bbcneandcumbria.uk", "BBC.One.NE.and.C.HD.uk"),
        (["BBC ONE CI FHD"], "bbconechannelislands.uk", "BBC.One.CI.HD.uk"),
        (["BBC ONE SOUTH HD"], "bbcsouth.uk", "BBC.One.Sth.HD.uk"),
        (["BBC ONE SOUTH EAST"], "bbcsoutheast.uk", "BBC.One.S.East.HD.uk"),
        (["BBC ONE SOUTH WEST"], "bbcsouthwest.uk", "BBC.One.S.West.HD.uk"),
        (["BBC ONE WEST"], "bbcwest.uk", "BBC.One.West.HD.uk"),
        (["BBC ONE WEST MIDLANDS SD"], "bbcwestmidlans.uk", "BBC.One.WM.HD.uk"),
        (["BBC ONE YORKSHIRE FHD"], "bbcyorkshire.uk", "BBC.One.Yorks.HD.uk"),
        (["BBC ONE EAST YORK/LINC FHD"], "bbcyourkshirelincolnshire.uk", "BBC.One.Y.and.L.HD.uk"),
        (["ITV 2 FHD", "ITV 2 HD", "ITV 2 SD"], "ITV2.uk", "ITV2.HD.uk"),
        (["ITV 3 FHD", "ITV 3 HD", "ITV 3 SD"], "ITV3.uk", "ITV3.HD.uk"),
        (["ITV 4 FHD", "ITV 4 HD", "ITV 4 SD"], "ITV4.uk", "ITV4.HD.uk"),
        (["ITV Quiz HD", "ITV QUIZ FHD"], "ITVQuiz.uk", "ITV.Quiz.uk"),
        (["E4 FHD", "E4 HD", "E4 SD"], "E4.uk", "E4.HD.uk"),
        (["E4 XTRA SD"], "E4Extra.uk", "E4.Extra.uk"),
        (["MORE 4 FHD", "MORE 4 HD", "MORE 4 SD"], "More4.uk", "More4.HD.uk"),
        (["FILM 4 FHD", "FILM 4 HD"], "Film4.uk", "Film4.HD.uk"),
        (["4 SEVEN SD"], "4seven.uk", "4seven.uk"),
        (["5 STAR"], "5STAR.uk", "5STAR.uk"),
        (["5 USA"], "5USA.uk", "5.USA.uk"),
        (["5 SELECT"], "5SELECT.uk", "5SELECT.uk"),
        (["5 ACTION SD"], "5Action.uk", "5ACTION.uk"),
        (["COMEDY CENTRAL FHD", "COMEDY CENTRAL HD", "COMEDY CENTRAL SD"], "ComedyCentral.uk", "ComedyCentHD.uk"),
        (["COMEDY XTRA SD"], "ComedyCentralExtra.uk", "ComedyXtra.uk"),
        (["CHALLENGE"], "Challenge.uk", "Challenge.uk"),
        (["SKY ARTS FHD", "SKY ARTS HD"], "SkyArts.uk", "Sky.Arts.HD.uk"),
        (["SKY ATLANTIC FHD", "SKY ATLANTIC HD"], "SkyAtlantic.uk", "Sky.Atlantic.HD.uk"),
        (["SKY COMEDY FHD", "SKY COMEDY HD"], "SkyComedy.uk", "Sky.Comedy.HD.uk"),
        (["SKY CRIME FHD", "SKY CRIME HD"], "SkyCrime.uk", "Sky.Crime.HD.uk"),
        (["SKY DOCUMENTARIES FHD", "SKY DOCUMENTARIES HD", "SKY DOCUMENTARIES SD"], "SkyDocumentaries.uk", "Sky.Documentaries.HD.uk"),
        (["SKY NATURE FHD", "SKY NATURE HD"], "SkyNature.uk", "Sky.Nature.HD.uk"),
        (["SKY KIDS FHD", "SKY KIDS HD"], "SkyKids.uk", "Sky.Kids.HD.uk"),
        (["SKY MIX FHD", "SKY MIX HD"], "SkyMix.uk", "Sky.Mix.HD.uk"),
        (["SKY WITNESS FHD", "SKY WITNESS HD"], "SkyWitness.uk", "Sky.Witness.HD.uk"),
        (["SKY SCI-FI FHD", "SKY SCI-FI HD"], "SkySci-Fi.uk", "Sky.Sci-Fi.HD.uk"),
        (["U&ALIBI FHD", "U&ALIBI HD"], "UAndAlibi.uk", "U.and.alibi.HD.uk"),
        (["U&GOLD FHD", "U&GOLD HD", "U&GOLD SD"], "UAndGold.uk", "U.and.GOLD.HD.uk"),
        (["U&DAVE FHD", "U&DAVE HD"], "UandDave.uk", "U.and.Dave.HD.uk"),
        (["U&DRAMA HD", "U&DRAMA SD"], "UandDrama.uk", "U.and.Drama.uk"),
        (["U&YESTERDAY SD"], "UandYesterday.uk", "U.and.YESTERDAY.uk"),
        (["U&Watch SD"], "UandW.uk", "U.and.W.HD.uk"),
        (["U&EDEN"], "UandEden.uk", "U.and.Eden.uk"),
        (["REALLY"], "Really.uk", "Really.uk"),
        (["QUEST FHD", "QUEST HD", "QUEST SD"], "Quest.uk", "QUEST.HD.uk"),
        (["QUEST RED"], "QuestRed.uk", "Quest.Red.uk"),
        (["DMAX SD"], "DMAX.uk", "DMAX.uk"),
        (["BLAZE"], "Blaze.uk", "BLAZE.uk"),
        (["PBS AMERICA"], "PBSAmerica.uk", "PBS.America.uk"),
        (["DISCOVERY FHD", "DISCOVERY HD", "DISCOVERY SD"], "DiscoveryChannel.uk", "Discovery.HD.uk"),
        (["DISCOVERY HISTORY SD"], "DiscoveryHistory.uk", "Disc.History.uk"),
        (["DISCOVERY SCIENCE SD"], "DiscoveryScience.uk", "Disc.Science.uk"),
        (["ANIMAL PLANET FHD"], "AnimalPlanet.uk", "Animal.Planet.uk"),
        (["NATIONAL GEOGRAPHIC FHD", "NATIONAL GEOGRAPHIC HD", "NATIONAL GEOGRAPHIC SD"], "NationalGeographicChannel.uk", "Nat.Geo.HD.uk"),
        (["NATIONAL GEOGRAPHIC WILD FHD", "NATIONAL GEOGRAPHIC WILD HD"], "NationalGeographicWild.uk", "NatGeoWild.HD.uk"),
        (["CRIME & INVESTIGATIONS FHD", "CRIME & INVESTIGATIONS HD", "CRIME & INVESTIGATIONS SD"], "Crime+Investigation.uk", "Crime+Inv.HD.uk"),
        (["INVESTIGATION DISCOVERY SD"], "InvestigationDiscovery.uk", "ID.uk"),
        (["TLC FHD", "TLC SD"], "TLC.uk", "TLC.HD.uk"),
        (["SKY CINEMA ACTION FHD", "SKY CINEMA ACTION HD", "SKY CINEMA ACTION SD"], "SkyCinemaAction.uk", "Sky.Action.HD.uk"),
        (["SKY CINEMA COMEDY FHD", "SKY CINEMA COMEDY HD", "SKY CINEMA COMEDY SD"], "SkyCinemaComedy.uk", "Sky.Cinema.Comedy.uk"),
        (["SKY CINEMA FAMILY FHD", "SKY CINEMA FAMILY HD", "SKY CINEMA FAMILY SD"], "SkyCinemaFamily.uk", "Sky.Family.HD.uk"),
        (["SKY CINEMA GREATS FHD", "SKY CINEMA GREATS HD", "SKY CINEMA GREATS SD"], "SkyCinemaGreats.uk", "Sky.Greats.HD.uk"),
        (["SKY CINEMA HITS FHD", "SKY CINEMA HITS HD", "SKY CINEMA HITS SD"], "SkyCinemaHits.uk", "Sky.Cinema.Hits.HD.uk"),
        (["SKY CINEMA PREMIER FHD", "SKY CINEMA PREMIER HD", "SKY CINEMA PREMIER SD"], "SkyCinemaPremiere.uk", "SkyPremiereHD.uk"),
        (["SKY CINEMA SciFi FHD", "SKY CINEMA SciFi HD", "SKY CINEMA SciFi SD"], "SkyCinemaSci-fiAndHorror.uk", "Sky.ScFi/HorHD.uk"),
        (["SKY CINEMA SELECT FHD", "SKY CINEMA SELECT HD", "SKY CINEMA SELECT SD"], "SkyCinemaSelect.uk", "Sky.Cinema.Select.uk"),
        (["SKY CINEMA THRILLER FHD", "SKY CINEMA THRILLER HD", "SKY CINEMA THRILLER SD"], "SkyCinemaThriller.uk", "Sky.Thriller.HD.uk"),
        (["CARTOON NETWORK FHD", "CARTOON NETWORK SD"], "CartoonNetwork.uk", "Cartoon.Net.HD.uk"),
        (["BOOMERANG FHD"], "Boomerang.uk", "Boomerang.HD.uk"),
        (["CARTOONITO SD"], "Cartoonito.uk", "Cartoonito.uk"),
        (["NICK HD"], "Nickelodeon.uk", "NickelodeonHD.uk"),
        (["NICK JR HD"], "NickJr.uk", "Nick.Jr..HD.uk"),
        (["NICK JR TOO"], "NickJrToo.uk", "Nick.Jr..Too.uk"),
        (["NICKTOONS"], "Nicktoons.uk", "Nicktoons.uk"),
        (["GB NEWS FHD", "GB NEWS HD", "GB NEWS SD"], "GBNews.uk", "GB.News.HD.uk"),
        (["CNN FHD"], "CNN.uk", "CNN.HD.uk"),
        (["BLOOMBERG FHD"], "Bloomberg.uk", "Bloomberg.HD.uk"),
        (["CNBC FHD"], "CNBC.uk", "CNBC.HD.uk"),
        (["FRANCE 24 HD"], "France24.uk", "FRANCE.24.HD.uk"),
        (["AL JAZEERA FHD", "AL JAZEERA SD"], "AlJazeeraEnglish.uk", "Al.Jazeera.HD.uk"),
        (["NHK WORLD HD"], "NHKWorld.uk", "NHK.World.HD.uk"),
        (["NHK WORLD FHD"], "nhkworldhd.uk", "NHK.World.HD.uk"),
        (["TRT WORLD FHD"], "TRTWorld.uk", "TRT.World.HD.uk"),
        (["TRT World FHD"], "trtworld.uk", "TRT.World.HD.uk"),
        (["Sky Sports Football FHD 50FPS", "Sky Sports Football FHD", "Sky Sports Football SD"], "SkySportsFootball.uk", "Sky.Sports.Football.HD.uk"),
        (["Sky Sports NFL HD"], "skysportsaction.uk", "Sky.Sports.NFL.uk"),
        (["Sky Sports Cricket FHD", "Sky Sports Cricket SD"], "SkySportsCricket.uk", "SkySpCricket.HD.uk"),
        (["Sky Sports Cricket HD", "Sky Sports Cricket FHD 50FPS"], "skysportscricket.uk", "SkySpCricket.HD.uk"),
        (["Sky Sports F1 FHD", "Sky Sports F1 SD"], "SkySportsF1.uk", "SkySp.F1.HD.uk"),
        (["Sky Sports F1 HD", "Sky Sports F1 FHD 50FPS"], "skysportsf1.uk", "SkySp.F1.HD.uk"),
        (["Sky Sports Golf FHD", "Sky Sports Golf SD"], "SkySportsGolf.uk", "SkySp.Golf.HD.uk"),
        (["Sky Sports Golf HD", "SKY SPORTS GOLF FHD 50FPS (UK)"], "skysportsgolf.uk", "SkySp.Golf.HD.uk"),
        (["Sky Sports Premier League FHD", "Sky Sports Premier League HD", "Sky Sports Premier League SD"], "SkySportsPremierLeague.uk", "SkySp.PL.HD.uk"),
        (["Sky Sports Premier League FHD 50FPS"], "skysportspremiereleague.uk", "SkySp.PL.HD.uk"),
        (["Sky Sports Tennis FHD", "Sky Sports Tennis HD", "Sky Sports Tennis SD"], "SkySportsTennis.uk", "SkySp.Tennis.HD.uk"),
        (["Sky Sports News FHD 50FPS", "Sky Sports News FHD", "Sky Sports News HD", "Sky Sports News SD"], "SkySportsNews.uk", "SkySp.News.HD.uk"),
        (["Sky Sports Racing FHD", "Sky Sports Racing SD", "Sky Sports Racing FHD 50FPS"], "SkySportsRacing.uk", "SkySp.Racing.HD.uk"),
        (["Sky Sports Racing HD"], "skysportsracing.uk", "SkySp.Racing.HD.uk"),
        (["Sky Sports+ FHD 50FPS", "Sky Sports+ FHD", "Sky Sports+ SD"], "SkySportsPlus.uk", "SkySp+HD.uk"),
        (["Sky Sports+ HD"], "skysportsplus.uk", "SkySp+HD.uk"),
        (["RACING TV FHD", "RACING TV HD", "RACING TV SD"], "RacingTV.uk", "Racing.TV.HD.uk"),
        (["Racing TV FHD 50FPS"], "racinguk.uk", "Racing.TV.HD.uk"),
        (["PREMIER SPORTS 1 FHD 50FPS (UK)", "PREMIER SPORTS 1 FHD (UK)", "PREMIER SPORTS 1 HD (UK)"], "PremierSports1.uk", "Premier.Sports.1.HD.uk"),
        (["PREMIER SPORTS 2 FHD 50FPS (UK)", "PREMIER SPORTS 2 FHD (UK)", "PREMIER SPORTS 2 HD (UK)"], "PremierSports2.uk", "Premier.Sports.2.HD.uk"),
        (["MUTV FHD", "MUTV HD"], "MUTV.uk", "MUTV.HD.uk"),
        (["LFC TV FHD", "LFC TV HD"], "LFCTV.uk", "LFCTV.HD.uk"),
        (["TNT Sports 1 HD"], "tntsports1.uk", "TNT.Sports.1.HD.uk")
    ]
}
