//
//  LumeTheme.swift
//  Lume
//
//  The app's own colour, taken from the logo's gradient (pink #FF8BD7 to
//  purple #7000B4) and tuned for legibility:
//
//  - Light: #8A1FC4 — 6.8:1 as text on white, 6.8:1 under a white label.
//  - Dark:  #B65CF0 — 5.8:1 as text on black, 4.7:1 on a raised dark
//    surface, 3.6:1 under a white label (bold button text).
//
//  The pair is the `LumeAccent` colour, and it appears only where a view asks
//  for `Color.lumeAccent` — one path, applied on purpose. It is deliberately
//  *not* the app's `AccentColor`: that tints system chrome implicitly — the
//  tvOS tab bar's selection, every plain form button — so setting it spread
//  the brand into places that read badly, in states hard to predict. With
//  `AccentColor` left to the system, controls look as the platform intends,
//  and nothing turns purple that no one chose.
//
//  `Color.lumeAccent` / `.lumeAccent` are generated by Xcode from
//  `Assets.xcassets/LumeAccent.colorset` — the single definition. Its `tv`
//  entries hold the dark value under both appearances: Lume's tvOS screens are
//  always dark, even on a TV set to a light appearance.
