//
//  LumeTheme.swift
//  Lume
//
//  The brand palette, from the redesign's foundations. Each role is a colour
//  set in `Assets.xcassets`, generated by Xcode as `Color.lume…`:
//
//  - `lumeAccent` — Lume pink: progress, selection, the mark. #FF88D7 on dark
//    (9.2:1 on Night) and on tvOS; #B8237F ("pink deep") in light appearance,
//    5.9:1 on white. White text on the dark pink is only 2.2:1, so anything
//    drawn *on* an accent fill uses `lumeOnAccent` (white on deep, Ink on pink,
//    8.7:1).
//  - `lumePinkDeep` — #B8237F everywhere: fills that carry a white glyph.
//  - `lumeNight` #0A0810 — the app ground behind artwork.
//  - `lumeInk` #14101F — the brand ground: launch, splash, player wait.
//  - `lumeViolet` #7000B4 — depth behind brand moments (the ambient glow);
//    never text.
//  - `lumeLiveRed` #D7263D — the LIVE badge fill.
//  - `lumeTextSecondary` / `lumeTextTertiary` — secondary and tertiary text:
//    #B9B5C4 / #8E8A99 on dark and tvOS, #55506A / #6F6A80 in light.
//  - `lumeSelection` — selected chips, tabs and rows: Lume pink at 18% on dark,
//    pink deep at 10% in light.
//  - `lumeGround` — the plain-screen ground: Night on dark, Day #F7F5FA in light.
//
//  Focus stays white, as tvOS draws it. Interface text is the system font;
//  Unbounded is the wordmark only (`LumeWordmark`).
//
//  On iPhone, iPad and Mac the accent is also the scene's tint, as the light
//  and dark foundations specify: selected tabs, primary buttons, links and
//  toggles, with destructive roles still the system red. It stays out of the
//  app's `AccentColor`, and tvOS sets no tint: there it would recolour the tab
//  bar's selection and the focus treatment, which stay as tvOS draws them.
//  The sets' `tv` entries hold the dark value under both appearances: Lume's
//  tvOS screens are always dark, even on a TV set to a light appearance.
